### ISSUE TITLE
redis存储问题

### ISSUE THREAD

**Issue by yangxiuyi001** [Hansin1997/captcha#9]
请问用分布式系统用redis存code，在存key的时候怎么制定Code的name属性的值

**Comment by Hansin1997** [comment]
你好，请问你说的存 key 的时候，是指的发送验证码的时候吗？

如果是的话，在 ```@SendCode``` 上添加 value 属性即可指定 code 的 名称：
```java
@SendCode(store = @Store("redisCodeStore"), value = "myCodeName")
```
指定 ```myCodeName``` 之后，记得在消费（验证）时也同样指定对应的名称：
```java
@VerifyCode(store = @Store("redisCodeStore"), value= "myCodeName")
```

---
另外，框架在进行 Redis 存储与获取时，会加上一些前缀，默认前缀是：```CAPTCHA_CODE```

如果需要自定义前缀，可以在配置文件 ```application.yaml``` 中配置：
```yaml
dustlight:
  captcha:
    store:
      redis:
        key-prefix: "CAPTCHA_CODE" # 自定义前缀
```

如果配置文件是 ```application.properties``` 依然同理。
